### ISSUE TITLE
Prefix is mandatory

### ISSUE THREAD

**Issue by miguelcnf** [statful/statful-client-vertx#19]
The prefix is no longer mandatory on the most recent spec of the clients.

**Comment by miguelcnf** [comment]
I thinking about removing the prefix configuration completely since it isn't used for identification anymore and actually prefixing a metric name can be achieved by the namespace configuration.

I believe this is what's in place in the java client already.

@reistiago thoughts?

**Comment by reistiago** [comment]
sounds good
