### ISSUE TITLE
Flush immediately when the buffer is full

### ISSUE THREAD

**Issue by hugocosta88** [statful/statful-client-vertx#4]
There are applications that have an big variation in the volume of metrics created during its execution. 
When those applications are sending a lot of metrics in a small period of time, they are reaching the buffer capacity. The buffer is being flushed at regular interval, so the client is rejecting the metrics that arrive after the buffer is full and before the flush operation is triggered (https://github.com/statful/statful-client-vertx/blob/master/src/main/java/com/statful/sender/MetricsHolder.java#L71).

One possible solution is to flush the buffer immediately when the maximum capacity is reached.
We would need to maintain the regular interval trigger to ensure that the flush operation is performed even when the volume of metrics is very small.

**Comment by miguelcnf** [comment]
This should already be fixed and released, feel free to re-open if that's not the case.
